### ISSUE TITLE
J'ai une petite question dans le fichier "server_client.sh"

### ISSUE THREAD

**Issue by mama3925** [Tonin386/LO14_project#2]
Dans le fichier "server_client.sh", et la ligne 47, vous avez écrit [ -e "FIFO" ] || mkfifo "$FIFO". Mais je pense qu'il faut être [-e "$FIFO"] || mkfifo "$FIFO", parce que vous avez déclaré et défini un variable FIFO avant, dans la ligne 36.
Je voudrais savoir si le Dollar est nésessaire ou non ?

**Comment by Tonin386** [comment]
Il semblerait bien, oui ! Le dollar est manquant et cela devrait être  [-e "$FIFO"]
Bien vu :)
